import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { cn } from "@/lib/utils"
import RainbowkitAndWagmiProvider from "./RainbowKitAndWagmiProvider";
import Layout from "@/components/Layout";

const fontSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          fontSans.className
        )}
      >
        <RainbowkitAndWagmiProvider>
          <Layout>
            {children}
          </Layout>
        </RainbowkitAndWagmiProvider>
      </body>
    </html>
  )
}
