name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: $
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Forge
      run: |
        OS=$(echo ${RUNNER_OS} |tr '[:upper:]' '[:lower:]')
        curl -L https://github.com/cwbaker/forge/releases/download/v0.9.0/forge-${OS}-v0.9.0.tar.gz > forge.tar.gz
        tar -xvf forge.tar.gz
      shell: bash
    - name: Build
      run: |
        forge/bin/forge variant=release
      shell: bash
