name: Test backend

on: [push]

jobs:
  test:
    name: Hardhat-Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        working-directory: ./backend
        with:
          version: nightly

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Hardhat tests
        working-directory: ./backend
        run: npx hardhat test
        shell: bash

      - name: Run Foundry tests
        run: forge test -vvv
